version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sqhg_user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: sqhg
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - sqhg-network

  app:
    build: .
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - sqhg-network

networks:
  sqhg-network:
    driver: bridge
